name: repeat_tutor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.19.1

  auto_route: ^10.3.0
  uuid: ^4.5.1
  markdown_widget: ^2.3.2+8
  showcaseview: ^5.0.1

  # plugins
  path_provider: ^2.1.5
  path: ^1.9.1
  share_plus: ^12.0.0
  permission_handler: ^11.3.1
  wakelock_plus: ^1.4.0
  package_info_plus: ^9.0.0

  # WebRTC
  flutter_webrtc: ^1.2.1

  # Audio
  just_audio: ^0.10.5
  record: ^6.1.2
  speech_to_text: ^7.3.0

  # REST API
  dio: ^5.9.0

  # State management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # Database
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  sqlite3: ^2.9.1
  sqlite3_flutter_libs: ^0.5.40

  # Metrics and Attribution
  apphud: ^2.7.1
  ab_test_service:
    git:
      url: https://github.com/RuslanTsitser/ab_test_service.git
      ref: 0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  auto_route_generator: ^10.3.0
  lean_builder: ^0.1.4

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  output_dir: lib/core/localization/generated
  arb_dir: lib/core/localization/l10n
