name: repeat_tutor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.19.1

  auto_route: ^10.3.0
  uuid: ^4.5.1
  markdown_widget: ^2.3.2+8
  showcaseview: ^5.0.1
  flutter_animate: ^4.5.2
  lucide_icons: ^0.257.0

  # plugins
  path_provider: ^2.1.5
  path: ^1.9.1
  share_plus: ^12.0.0
  permission_handler: ^11.3.1
  wakelock_plus: ^1.4.0
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.4

  # WebRTC
  flutter_webrtc: ^1.2.1

  # Audio
  just_audio: ^0.10.5
  record: ^6.1.2
  speech_to_text: ^7.3.0

  # REST API
  dio: ^5.9.0

  # State management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # Database
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  sqlite3: ^2.9.1
  sqlite3_flutter_libs: ^0.5.40

  # Metrics and Attribution
  apphud: ^2.7.1
  ab_test_service:
    git:
      url: https://github.com/RuslanTsitser/ab_test_service.git
      ref: 0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  auto_route_generator: ^10.3.0
  lean_builder: ^0.1.4
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  intl_utils: ^2.8.10

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.webp
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
  output_dir: lib/core/localization/generated
  arb_dir: lib/core/localization/l10n

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  # min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"
